Add example typescript preact
brillout/vite-plugin-ssr pull request #255
Opened 2022-02-05 10:00 UTC by bnn1

`preact` folder is server-side routing
`preact-full` folder is client-side routing

2022-02-05 10:07 UTC, brillout commented
I'm actually going to rename the examples `react` to `react-server-routing` and `react-full` to `react-client-routing`; we can already starting following that convention for this PR.

The tests are failing.

2022-02-05 10:11 UTC, bnn1 commented
@brillout  
Tests are failing because test suit does not know that it needs to install dependencies for added examples (I think). If I skip TS checks my examples aren't being tested for the same reason. 

I couldn't figure out how to add my examples to test suit.

2022-02-05 10:14 UTC, brillout commented
``Error: Command `npx tsc --noEmit` failed [cwd: /home/runner/work/vite-plugin-ssr/vite-plugin-ssr/examples/preact-full]``

Make sure `npx tsc --noEmit` doesn't throw when ran at `/examples/preact-full`.

2022-02-05 11:43 UTC, brillout commented
- Remove TS altogether
 - Rename directories to `examples/preact-server-routing` and `examples/preact-client-routing`.

2022-02-05 14:14 UTC, bnn1 commented
@brillout done

2022-02-05 20:42 UTC, brillout requested changes

2022-02-05 20:42 UTC, brillout commented on examples/preact-server-routing/renderer/_default.page.client.jsx
> +  if (body) {
I believe `body` is always defined.

2022-02-05 20:42 UTC, brillout commented on examples/preact-server-routing/server/index.js
> +// @ts-nocheck
We don't need this anymore

2022-02-06 10:29 UTC, brillout commented
Let's see if the boilerplate test run passes.

2022-02-06 11:30 UTC, brillout approved these changes

2022-02-07 21:41 UTC, merged